import type { InsertQuestion } from "@shared/schema";

// Questions from the Risk_App_Scoring_Engine_Clean_NoLinkedSources.xlsx
// 20 questions across 3 pillars: Safety (40%), WorkersComp (20%), Fleet (40%)
export const QUESTIONS_DATA: InsertQuestion[] = [
  // SAFETY PILLAR - 8 questions (Weight share: 0.4)
  {
    id: "SAF-01",
    pillar: "Safety",
    topic: "Safety Program",
    text: "How comprehensive is the organization's written safety program?",
    weight: "0.0600",
    scaleNotes: "1=No program, 2=Basic/incomplete, 3=Moderate, 4=Comprehensive, 5=Industry-leading",
    constraints: "Look for documented policies, procedures, and regular updates. Consider OSHA compliance.",
    sortOrder: 1,
  },
  {
    id: "SAF-02",
    pillar: "Safety",
    topic: "Safety Program",
    text: "How effective is safety training for employees?",
    weight: "0.0500",
    scaleNotes: "1=None, 2=Minimal, 3=Basic training, 4=Regular comprehensive, 5=Continuous improvement",
    constraints: "Evaluate training frequency, documentation, and effectiveness metrics.",
    sortOrder: 2,
  },
  {
    id: "SAF-03",
    pillar: "Safety",
    topic: "Incident Management",
    text: "How well does the organization manage and investigate incidents?",
    weight: "0.0500",
    scaleNotes: "1=No process, 2=Reactive only, 3=Basic investigation, 4=Root cause analysis, 5=Proactive prevention",
    constraints: "Review incident investigation procedures and corrective action implementation.",
    sortOrder: 3,
  },
  {
    id: "SAF-04",
    pillar: "Safety",
    topic: "Incident Management",
    text: "What is the organization's safety culture like?",
    weight: "0.0500",
    scaleNotes: "1=Poor/non-existent, 2=Compliance-focused, 3=Developing, 4=Strong, 5=Best-in-class",
    constraints: "Consider employee engagement, reporting culture, and management commitment.",
    sortOrder: 4,
  },
  {
    id: "SAF-05",
    pillar: "Safety",
    topic: "Hazard Control",
    text: "How effective are hazard identification and control measures?",
    weight: "0.0450",
    scaleNotes: "1=None, 2=Reactive, 3=Basic controls, 4=Proactive, 5=Leading practices",
    constraints: "Evaluate job hazard analyses, PPE programs, and engineering controls.",
    sortOrder: 5,
  },
  {
    id: "SAF-06",
    pillar: "Safety",
    topic: "Hazard Control",
    text: "How well maintained is safety equipment and PPE?",
    weight: "0.0450",
    scaleNotes: "1=Poor, 2=Inconsistent, 3=Adequate, 4=Well-maintained, 5=Excellent program",
    constraints: "Review inspection schedules, replacement policies, and employee compliance.",
    sortOrder: 6,
  },
  {
    id: "SAF-07",
    pillar: "Safety",
    topic: "Leadership",
    text: "How committed is leadership to safety initiatives?",
    weight: "0.0500",
    scaleNotes: "1=No commitment, 2=Minimal, 3=Moderate support, 4=Strong commitment, 5=Champions safety",
    constraints: "Look for visible leadership involvement, resource allocation, and safety metrics in goals.",
    sortOrder: 7,
  },
  {
    id: "SAF-08",
    pillar: "Safety",
    topic: "Leadership",
    text: "How well are safety metrics tracked and acted upon?",
    weight: "0.0500",
    scaleNotes: "1=Not tracked, 2=Basic tracking, 3=Regular review, 4=Data-driven decisions, 5=Predictive analytics",
    constraints: "Evaluate leading and lagging indicators, trend analysis, and action plans.",
    sortOrder: 8,
  },

  // WORKERS' COMP PILLAR - 4 questions (Weight share: 0.2)
  {
    id: "WC-01",
    pillar: "WorkersComp",
    topic: "Claims Management",
    text: "How effective is the workers' compensation claims management process?",
    weight: "0.0600",
    scaleNotes: "1=Poor, 2=Reactive, 3=Standard, 4=Proactive, 5=Best practices",
    constraints: "Review claims frequency, severity, and return-to-work programs.",
    sortOrder: 9,
  },
  {
    id: "WC-02",
    pillar: "WorkersComp",
    topic: "Claims Management",
    text: "How well does the organization manage return-to-work programs?",
    weight: "0.0500",
    scaleNotes: "1=None, 2=Basic, 3=Moderate, 4=Comprehensive, 5=Industry-leading",
    constraints: "Evaluate modified duty availability, physician communication, and outcomes.",
    sortOrder: 10,
  },
  {
    id: "WC-03",
    pillar: "WorkersComp",
    topic: "Medical Management",
    text: "How effective is the medical provider network management?",
    weight: "0.0450",
    scaleNotes: "1=No network, 2=Limited, 3=Adequate network, 4=Strong network, 5=Optimized care",
    constraints: "Consider network quality, access to specialists, and cost management.",
    sortOrder: 11,
  },
  {
    id: "WC-04",
    pillar: "WorkersComp",
    topic: "Medical Management",
    text: "How well are ergonomic risks addressed in the workplace?",
    weight: "0.0450",
    scaleNotes: "1=Not addressed, 2=Minimal, 3=Basic program, 4=Comprehensive, 5=Proactive prevention",
    constraints: "Evaluate workstation assessments, equipment, and training programs.",
    sortOrder: 12,
  },

  // FLEET PILLAR - 8 questions (Weight share: 0.4)
  {
    id: "FLT-01",
    pillar: "Fleet",
    topic: "Driver Management",
    text: "How rigorous is the driver hiring and screening process?",
    weight: "0.0600",
    scaleNotes: "1=Minimal, 2=Basic background, 3=Standard DOT, 4=Enhanced screening, 5=Comprehensive",
    constraints: "Review MVR checks, drug testing, reference verification, and hiring criteria.",
    sortOrder: 13,
  },
  {
    id: "FLT-02",
    pillar: "Fleet",
    topic: "Driver Management",
    text: "How effective is the ongoing driver training program?",
    weight: "0.0500",
    scaleNotes: "1=None, 2=Initial only, 3=Annual, 4=Regular/targeted, 5=Continuous improvement",
    constraints: "Evaluate defensive driving, vehicle-specific training, and refresher courses.",
    sortOrder: 14,
  },
  {
    id: "FLT-03",
    pillar: "Fleet",
    topic: "Driver Management",
    text: "How well is driver behavior monitored and managed?",
    weight: "0.0450",
    scaleNotes: "1=Not monitored, 2=Reactive, 3=Basic telematics, 4=Active coaching, 5=Predictive management",
    constraints: "Consider telematics usage, coaching programs, and performance metrics.",
    sortOrder: 15,
  },
  {
    id: "FLT-04",
    pillar: "Fleet",
    topic: "Vehicle Maintenance",
    text: "How comprehensive is the preventive maintenance program?",
    weight: "0.0500",
    scaleNotes: "1=Reactive only, 2=Basic PM, 3=Standard schedule, 4=Comprehensive, 5=Predictive maintenance",
    constraints: "Review maintenance schedules, documentation, and vehicle condition.",
    sortOrder: 16,
  },
  {
    id: "FLT-05",
    pillar: "Fleet",
    topic: "Vehicle Maintenance",
    text: "How well are pre-trip and post-trip inspections conducted?",
    weight: "0.0450",
    scaleNotes: "1=Not done, 2=Inconsistent, 3=Basic compliance, 4=Thorough, 5=Best practices",
    constraints: "Evaluate inspection documentation, defect reporting, and follow-up.",
    sortOrder: 17,
  },
  {
    id: "FLT-06",
    pillar: "Fleet",
    topic: "Vehicle Safety",
    text: "What level of vehicle safety technology is implemented?",
    weight: "0.0450",
    scaleNotes: "1=None, 2=Basic, 3=Standard features, 4=Advanced systems, 5=Full ADAS suite",
    constraints: "Consider cameras, collision avoidance, lane departure, and telematics.",
    sortOrder: 18,
  },
  {
    id: "FLT-07",
    pillar: "Fleet",
    topic: "Compliance",
    text: "How well does the organization maintain DOT/FMCSA compliance?",
    weight: "0.0500",
    scaleNotes: "1=Non-compliant, 2=Reactive, 3=Basic compliance, 4=Proactive, 5=Exceeds requirements",
    constraints: "Review CSA scores, audit history, and HOS compliance.",
    sortOrder: 19,
  },
  {
    id: "FLT-08",
    pillar: "Fleet",
    topic: "Compliance",
    text: "How effective is the accident prevention and response program?",
    weight: "0.0550",
    scaleNotes: "1=None, 2=Basic response, 3=Standard protocols, 4=Comprehensive, 5=Proactive prevention",
    constraints: "Evaluate accident reporting, investigation, and prevention initiatives.",
    sortOrder: 20,
  },
];
