import type { InsertQuestion } from "@shared/schema";

export const QUESTIONS_DATA: InsertQuestion[] = [
  {
    id: "SAF-01",
    pillar: "Safety",
    topic: "Policy Review & Leadership",
    text: "Is there a formal safety policy, how often is it reviewed, and how is executive leadership involved in supporting and enforcing safety expectations?",
    weight: "0.0400",
    scaleNotes: "1=No formal review; leadership unclear.\n2=Reviewed >24 months ago; limited/unclear leadership.\n3=Reviewed within 12\u201324 months; some leadership participation.\n4=Reviewed within last 12 months; defined leadership roles involved.\n5=Reviewed within last 12 months; includes executive-level participation.",
    constraints: "Constraint: if not reviewed on a defined interval, cap at 3.",
    sortOrder: 1,
  },
  {
    id: "SAF-02",
    pillar: "Safety",
    topic: "Training (Hire + Method + Verification)",
    text: "At what point do employees receive safety training, how often is it conducted, by what methods, and how is understanding or competency verified?",
    weight: "0.0800",
    scaleNotes: "1=Infrequent/ad hoc; employees may work before training; passive; no verification.\n2=Scheduled but employees may work before training; limited verification.\n3=Training at/before time of hire + cadence; mostly classroom/online; limited verification.\n4=Training at/before time of hire + routine cadence; hands-on/field; documented observation/coaching.\n5=Training at/before time of hire + cadence AND triggers; verified via observation/coaching and follow-up.",
    constraints: "Constraint: if employees work before training, cap at 2.",
    sortOrder: 2,
  },
  {
    id: "SAF-03",
    pillar: "Safety",
    topic: "Incidents & Near-Misses (System Fixes)",
    text: "How are safety incidents and near-misses investigated, how are deficiencies in safety management systems identified, and how are those deficiencies corrected?",
    weight: "0.0600",
    scaleNotes: "1=Reactive; near-misses rarely reported; actions informal; no verification.\n2=Documented but shallow; near-miss inconsistent; actions delayed/closed without verification.\n3=Defined process for incidents+near-misses; owners/due dates; limited effectiveness verification.\n4=Prompt structured investigations; system fixes implemented; follow-up verifies effectiveness.\n5=Root-cause + risk prioritization; leadership reviews trends; effectiveness verified over time.",
    constraints: "Constraint: if near-misses not reviewed, cap at 2. If only employee blame, cap at 3.",
    sortOrder: 3,
  },
  {
    id: "SAF-04",
    pillar: "Safety",
    topic: "Supervisor Observations & Coaching (System Focus)",
    text: "How do supervisors conduct safety observations, provide coaching, and address system-level contributors rather than placing blame solely on employees?",
    weight: "0.0800",
    scaleNotes: "1=Rare/reactive or punitive; rule-violation focused; no follow-up.\n2=Occasional and documented; mostly behavior-focused; limited escalation/system fixes.\n3=Routine observations; some system issues; follow-up inconsistent.\n4=Routine and system-focused; issues documented/escalated; actions verified.\n5=Embedded practice; trend review; coaching drives system change; effectiveness verified.",
    constraints: "Constraint: if observations are primarily punitive/behavior-only, cap at 2.",
    sortOrder: 4,
  },
  {
    id: "SAF-05",
    pillar: "Safety",
    topic: "Frontline Hazard Reporting (No Fear + Feedback)",
    text: "How do frontline employees report hazards and unsafe conditions without fear of reprisal, and how are those reports tracked, addressed, and communicated back?",
    weight: "0.0800",
    scaleNotes: "1=Reporting unclear/limited; fear of discipline; little tracking/response.\n2=Mechanism exists but low trust; inconsistent tracking/response; little feedback.\n3=Clear reporting without fear; tracked/addressed; mostly reactive; participation not reinforced.\n4=Actively encouraged; timely response; feedback provided; leadership supports reporting.\n5=Embedded and reinforced; recognition/rewards; trends reviewed; employee input shapes improvements.",
    constraints: "Constraint: if reporting leads to blame/discipline, cap at 1. If no feedback loop, cap at 3.",
    sortOrder: 5,
  },
  {
    id: "SAF-06",
    pillar: "Safety",
    topic: "Management Review & Action (Decisions + Follow-through)",
    text: "How does management review safety performance, what decisions are made as a result, and how is follow-through verified?",
    weight: "0.0600",
    scaleNotes: "1=Rare/symbolic; reactive; no documented actions/verification.\n2=Periodic but passive; mostly lagging metrics; limited/unresourced actions.\n3=Regular structured reviews include some leading indicators; inconsistent follow-through.\n4=Regular leading+lagging review; owners assigned; resources allocated; completion verified.\n5=Strategic integration; decisions affect staffing/scheduling/capital; leadership accountable; effectiveness verified.",
    constraints: "Constraint: if lagging-only review, cap at 2. If actions not resourced, cap at 3.",
    sortOrder: 6,
  },
  {
    id: "WC-01",
    pillar: "WorkersComp",
    topic: "Injury Reporting Timeliness & Accountability",
    text: "How are work-related injuries reported, who is responsible for reporting, and how is timely reporting enforced to preserve medical-only and return-to-work outcomes?",
    weight: "0.0400",
    scaleNotes: "1=Expectations unclear; employees self-decide; supervisor role undefined; delays common.\n2=Policy exists but weak communication/enforcement; delays frequent.\n3=Roles defined; most injuries reported timely; monitoring/enforcement inconsistent.\n4=All injuries required; supervisors escalate; timeliness tracked; delays addressed.\n5=Immediate reporting embedded; metrics tracked and improved.",
    constraints: "Constraint: delayed reporting that prevents early medical intervention/RTW caps at 2.",
    sortOrder: 7,
  },
  {
    id: "WC-02",
    pillar: "WorkersComp",
    topic: "Medical Direction (Clinics + Nurse Triage + Telemedicine)",
    text: "How is medical care directed following an injury, including use of nurse triage, telemedicine, and vetted occupational medical providers?",
    weight: "0.0400",
    scaleNotes: "1=Uncontrolled entry; no direction/triage; restrictions unmanaged.\n2=Informal/inconsistent direction; triage/telemed optional/rare.\n3=Generally directed to occupational care/triage; limited coordination.\n4=Directed to vetted clinics/triage/telemed as appropriate; coordinated; restrictions managed.\n5=Integrated triage/telemed + vetted clinics; proactive restriction management; multi-state ready.",
    constraints: "Constraint: if employees choose initial providers without direction, cap at 2. For remote/multi-state, no triage/telemed caps at 3.",
    sortOrder: 8,
  },
  {
    id: "WC-03",
    pillar: "WorkersComp",
    topic: "Return-to-Work Execution (Transitional Duty)",
    text: "How does the organization implement and manage return-to-work or transitional duty to reduce lost time and support recovery?",
    weight: "0.0400",
    scaleNotes: "1=No RTW; off work until fully released.\n2=RTW policy exists but avoided; options limited; lost-time common.\n3=Options exist; used reactively; inconsistent by supervisor/location.\n4=Early and consistent RTW; tasks pre-identified; restrictions accommodated.\n5=Embedded RTW; supervisors accountable; outcomes tracked and improved.",
    constraints: "Constraint: if transitional duty not identified in advance, cap at 3. If supervisors resist restrictions, cap at 2.",
    sortOrder: 9,
  },
  {
    id: "WC-04",
    pillar: "WorkersComp",
    topic: "Claim Oversight (Ownership to Closure)",
    text: "Who is responsible for managing workers\u2019 compensation claims from initial report through closure, and how is progress monitored?",
    weight: "0.0300",
    scaleNotes: "1=No internal ownership; carrier-only; minimal employee contact.\n2=Informal ownership; inconsistent follow-up/communication.\n3=Defined role exists; periodic oversight; inconsistent escalation.\n4=Clear owner follows claims to closure; regular reviews; barriers addressed.\n5=Proactive owner; early escalation; coordinated with carrier; timely resolution.",
    constraints: "Constraint: if no specific internal role follows claims to closure, cap at 2. Renewal-only review caps at 2.",
    sortOrder: 10,
  },
  {
    id: "WC-05",
    pillar: "WorkersComp",
    topic: "Claims Review Intervals (Open Claims + Trends + Action)",
    text: "At what intervals are workers\u2019 compensation claims reviewed, and how are open claims, trends, and corrective actions tracked?",
    weight: "0.0300",
    scaleNotes: "1=No structured review; open claims drift.\n2=Infrequent/renewal-only; little action.\n3=Single cadence (e.g., quarterly); limited tracking of actions.\n4=Multi-interval reviews (e.g., monthly open-claim + quarterly trends); actions assigned/tracked.\n5=Dynamic cadence + triggers; drives closure and prevention; effectiveness monitored.",
    constraints: "Constraint: renewal-only caps at 2. If open claims not reviewed regularly to drive closure, cap at 3.",
    sortOrder: 11,
  },
  {
    id: "WC-06",
    pillar: "WorkersComp",
    topic: "Employee Trust & Check-In Cadence",
    text: "Who maintains contact with injured employees, how often do check-ins occur, and how is trust maintained throughout the claim?",
    weight: "0.0200",
    scaleNotes: "1=No owner/cadence; reactive contact only.\n2=Informal/irregular check-ins; employees unsure who to contact.\n3=Defined role; periodic check-ins but inconsistent.\n4=Clear owner; defined regular check-ins; employees understand process.\n5=Structured cadence + milestones; proactive, trust-centered engagement.",
    constraints: "Constraint: if no specific internal role owns check-ins, cap at 2. If no defined cadence, cap at 3.",
    sortOrder: 12,
  },
  {
    id: "FL-01",
    pillar: "Fleet",
    topic: "Fleet Safety Policy (Review + Executive Support)",
    text: "Is there a formal fleet safety policy, how often is it reviewed, and how is executive leadership involved in supporting and enforcing fleet safety expectations?",
    weight: "0.0500",
    scaleNotes: "1=No formal fleet policy; roles/expectations unclear.\n2=Policy exists but not operationalized; review infrequent; leadership distant.\n3=Policy defined; periodic review; limited leadership involvement.\n4=Reviewed on defined interval; leadership supports and enforces expectations.\n5=Embedded executive ownership; resourced and consistently enforced.",
    constraints: "Constraint: if not reviewed on a defined interval OR no visible exec support, cap at 3.",
    sortOrder: 13,
  },
  {
    id: "FL-02",
    pillar: "Fleet",
    topic: "Driver Qualification + MVR Monitoring (Annual vs Continuous)",
    text: "How are drivers qualified and authorized, how are motor vehicle records monitored (annually or continuously), and how are changes in driver risk addressed?",
    weight: "0.0800",
    scaleNotes: "1=No MVR oversight; no authorization control.\n2=One-time/infrequent; assumes carrier monitors MVRs.\n3=Defined annual/periodic MVR review; response to changes may be slow.\n4=Active monitoring (regular or third-party); triggers actions.\n5=Continuous monitoring with timely intervention; authorization reflects current risk.",
    constraints: "Constraint: if assumes carrier monitors MVRs, cap at 2. Hire-only/infrequent caps at 2.",
    sortOrder: 14,
  },
  {
    id: "FL-03",
    pillar: "Fleet",
    topic: "Driver Training (Condition-Based + Verified)",
    text: "How are drivers trained and coached, how often does training occur, how is it verified, and how is training adapted to the driving conditions and locations drivers encounter?",
    weight: "0.0600",
    scaleNotes: "1=Minimal/generic; not adapted to locations/conditions; no verification.\n2=Periodic but non-specific; limited coaching.\n3=Defined hire + periodic; limited adaptation/verification.\n4=Condition-based (e.g., winter/urban); verified via observation/ride-alongs/performance.\n5=Dynamic coaching; adapted to geography/season/routes; driven by trends/telematics.",
    constraints: "Constraint: if training not adapted to actual conditions/locations, cap at 2. If not verified, cap at 3.",
    sortOrder: 15,
  },
  {
    id: "FL-04",
    pillar: "Fleet",
    topic: "Journey Management (Routine + High-Frequency Trips)",
    text: "How are work-related driving journeys\u2014including routine and frequently traveled routes\u2014evaluated for risk, and how are high-risk trips mitigated or avoided?",
    weight: "0.0700",
    scaleNotes: "1=No journey evaluation; driver-only judgment.\n2=Selective; routine routes not assessed; responsibility unclear.\n3=Defined but incomplete; routine reassessment inconsistent.\n4=All journeys incl. routine evaluated; periodic reassessment; mitigations applied.\n5=Embedded + dynamic; routine routes reassessed and adjusted; trips avoided/mitigated using data.",
    constraints: "Constraint: if routine/frequent routes not periodically reassessed, cap at 2.",
    sortOrder: 16,
  },
  {
    id: "FL-05",
    pillar: "Fleet",
    topic: "Behavior Monitoring + Intervention (Duty to Act)",
    text: "How is driver behavior monitored, who reviews driving data, and how are coaching or corrective actions taken to address risk?",
    weight: "0.0700",
    scaleNotes: "1=No monitoring; learns after incidents.\n2=Data exists but not reviewed/acted; responsibility unclear.\n3=Periodic review; inconsistent coaching/follow-up.\n4=Defined cadence; clear owner; consistent coaching/corrective actions.\n5=Proactive monitoring + triggers; timely coaching; interventions documented.",
    constraints: "Constraint: if data collected but not acted upon, cap at 2. Unused data increases legal exposure.",
    sortOrder: 17,
  },
  {
    id: "FL-06",
    pillar: "Fleet",
    topic: "Driver Engagement (Reinforcement + Participation)",
    text: "How are drivers actively engaged in fleet safety, including positive reinforcement, participation initiatives, and safe reporting of concerns?",
    weight: "0.0400",
    scaleNotes: "1=No engagement; no reinforcement; reporting minimal.\n2=Passive/occasional engagement; inconsistent reinforcement.\n3=Defined mechanisms but participation inconsistent.\n4=Active reinforcement; constructive use of data; reporting encouraged and responded to.\n5=Embedded and motivating; transparent constructive data use; high participation; no fear reporting.",
    constraints: "Constraint: if data used only for discipline/surveillance, cap at 2. No positive reinforcement caps at 3.",
    sortOrder: 18,
  },
  {
    id: "FL-07",
    pillar: "Fleet",
    topic: "Fleet Incidents + Near-Miss Learning",
    text: "How are fleet incidents and near-misses reported, investigated, and used to improve training, journey planning, or fleet controls?",
    weight: "0.0200",
    scaleNotes: "1=Reactive only; near-misses not reviewed; no systemic change.\n2=Documented but blame-focused; near-miss rare.\n3=Defined but inconsistent corrective actions.\n4=Structured learning applied to training/journeys/controls.\n5=Integrated learning loop; effectiveness reviewed to prevent recurrence.",
    constraints: "Constraint: if near-misses not reviewed, cap at 2. Driver-fault-only caps at 3.",
    sortOrder: 19,
  },
  {
    id: "FL-08",
    pillar: "Fleet",
    topic: "Management Review + Accountability (Fleet)",
    text: "How does leadership review fleet risk performance, assign accountability, and take action based on fleet risk metrics?",
    weight: "0.0100",
    scaleNotes: "1=No management review; accountability unclear.\n2=Infrequent/passive; little action.\n3=Periodic review; limited ownership/follow-through.\n4=Active review; named accountability; decisions change controls.\n5=Embedded executive accountability; resources allocated; outcomes monitored.",
    constraints: "Constraint: if no defined cadence, cap at 2. If accountability diffused, cap at 3.",
    sortOrder: 20,
  },
];
