name: Build, Deploy to gh-pages
on: 
  workflow_dispatch:
  pull_request:
    branches:
      - "prod"
    types: [opened, edited, reopened]
permissions:
  contents: write
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Build
        run: |
          npm i
          npm run build
          touch out/.nojekyll
        # Tests will be here
      - name: Deploy
        # https://github.com/JamesIves/github-pages-deploy-action
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: out
      - name: Create env file
        run: |
          touch .env
          echo NEXT_PUBLIC_TG_TOKEN=${NEXT_PUBLIC_TG_TOKEN} >> .env
          echo NEXT_PUBLIC_TG_CHAT_ID=${NEXT_PUBLIC_TG_CHAT_ID} >> .env
          cat .env
        env: 
          NEXT_PUBLIC_TG_TOKEN: ${{ secrets.TG_TOKEN }}
          NEXT_PUBLIC_TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
